// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcwwqDpx7hn2eqmxFyMhzulA1lA9rWoOI',
    appId: '1:708549433385:web:9f0afdb8452bea2ffd6438',
    messagingSenderId: '708549433385',
    projectId: 'travel-app-27fe1',
    authDomain: 'travel-app-27fe1.firebaseapp.com',
    storageBucket: 'travel-app-27fe1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBokKiszBIkmoksfGuaCbx_9d7Shjhyd9o',
    appId: '1:708549433385:android:a064f3f3700578ecfd6438',
    messagingSenderId: '708549433385',
    projectId: 'travel-app-27fe1',
    storageBucket: 'travel-app-27fe1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATPJJo5csRBLScWESa8TFwFEKbMEUDIo4',
    appId: '1:708549433385:ios:02291580bfe39714fd6438',
    messagingSenderId: '708549433385',
    projectId: 'travel-app-27fe1',
    storageBucket: 'travel-app-27fe1.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );
}
